name: release

on:
  push:
    tags:
      - 'v*'          # baut & released bei Tags wie v0.1.0
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag (z. B. v0.1.0), der in allen Repos ausgecheckt und für das Release verwendet werden soll'
        required: true
        type: string

concurrency:
  group: moddex-release-${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tag || github.ref_name }}
  cancel-in-progress: false

jobs:
  build-package:
    runs-on: ubuntu-22.04
    permissions:
      contents: write   # nötig für Release-Upload
    env:
      # Bei manuellem Lauf kommt der Tag aus dem Input, sonst aus dem Tag-Ref
      TARGET_REF: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tag || github.ref_name }}

    steps:
      # 1) Dieses (Packaging-)Repo
      - name: Checkout packaging repo (this)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # falls du Tag-Infos brauchst

      # 2) Backend-Repo (privat) – gleicher Tag wie Trigger/Manuell
      - name: Checkout backend at same tag
        uses: actions/checkout@v4
        with:
          repository: aklozyp/Moddex-Backend
          ref: ${{ env.TARGET_REF }}
          path: Moddex-Backend
          token: ${{ secrets.GH_TOKEN }}   # fine-grained PAT mit Contents: Read

      # 3) Frontend-Repo (privat) – gleicher Tag wie Trigger/Manuell
      - name: Checkout frontend at same tag
        uses: actions/checkout@v4
        with:
          repository: aklozyp/Moddex-Frontend
          ref: ${{ env.TARGET_REF }}
          path: Moddex-Frontend
          token: ${{ secrets.GH_TOKEN }}

      # 4) Java 21 + Maven-Cache
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      # 5) Backend bauen (über mvnw im Backend-Ordner)
      - name: Build backend JAR
        run: |
          chmod +x Moddex-Backend/mvnw
          Moddex-Backend/mvnw -f Moddex-Backend/pom.xml -B -DskipTests clean package
      - name: Collect backend artifact
        run: |
          mkdir -p build/backend
          cp Moddex-Backend/target/*.jar build/backend/Moddex-Backend.jar

      # 6) Node 20 + npm-Cache
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'Moddex-Frontend/package-lock.json'

      # 7) Frontend bauen
      - name: Build frontend dist
        run: |
          pushd Moddex-Frontend
          npm ci
          npm run build --if-present || npm run build
          popd
          mkdir -p build/frontend
          rsync -a --delete Moddex-Frontend/dist/ build/frontend/

      # 8) Bundle zusammenstellen (Skripte/Templates + Artefakte)
      - name: Assemble bundle
        run: |
          mkdir -p bundle/scripts bundle/packaging/systemd bundle/packaging/caddy bundle/config/defaults bundle/frontend bundle/backend
          # Artefakte
          cp -r build/frontend/* bundle/frontend/
          cp -r build/backend/Moddex-Backend.jar bundle/backend/
          # Packaging-Inhalte aus DIESEM Repo
          cp -r scripts/* bundle/scripts/
          cp -r packaging/systemd/* bundle/packaging/systemd/
          cp -r packaging/caddy/* bundle/packaging/caddy/
          if [ -d config/defaults ]; then cp -r config/defaults/* bundle/config/defaults/ || true; fi

          # Tarball + Checksum
          tar -C bundle -czf moddex-$TARGET_REF-linux-amd64.tar.gz .
          sha256sum moddex-$TARGET_REF-linux-amd64.tar.gz > moddex-$TARGET_REF-SHA256SUMS

      # 9) Release erstellen und Assets hochladen
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TARGET_REF }}
          files: |
            moddex-${{ env.TARGET_REF }}-linux-amd64.tar.gz
            moddex-${{ env.TARGET_REF }}-SHA256SUMS
