name: release

on:
  push:
    tags:
      - 'v*'          # baut & released bei Tags wie v0.1.0

concurrency:
  group: moddex-release-${{ github.ref_name }}
  cancel-in-progress: false

jobs:
  build-package:
    runs-on: ubuntu-22.04
    permissions:
      contents: write   # nötig für Release-Upload

    steps:
      # 1) Dieses (Packaging-)Repo
      - name: Checkout packaging repo (this)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # falls du Tag-Infos brauchst

      # 2) Backend-Repo (privat) – gleicher Tag wie Trigger
      - name: Checkout backend at same tag
        uses: actions/checkout@v4
        with:
          repository: aklozyp/Moddex-Backend
          ref: ${{ github.ref_name }}
          path: Moddex-Backend
          token: ${{ secrets.GH_TOKEN }}   # fine-grained PAT mit Contents: Read

      # 3) Frontend-Repo (privat) – gleicher Tag wie Trigger
      - name: Checkout frontend at same tag
        uses: actions/checkout@v4
        with:
          repository: aklozyp/Moddex-Frontend
          ref: ${{ github.ref_name }}
          path: Moddex-Frontend
          token: ${{ secrets.GH_TOKEN }}

      # 4) Java 21 + Maven-Cache
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven   # aktiviert Maven-Dependency-Cache (lokales Repo) :contentReference[oaicite:2]{index=2}

      # 5) Backend bauen (über mvnw im Backend-Ordner)
      - name: Build backend JAR
        run: |
          chmod +x Moddex-Backend/mvnw
          Moddex-Backend/mvnw -f Moddex-Backend/pom.xml -B -DskipTests clean package
      - name: Collect backend artifact
        run: |
          mkdir -p build/backend
          cp Moddex-Backend/target/*.jar build/backend/Moddex-Backend.jar

      # 6) Node 20 + npm-Cache
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'                                  # npm-Cache aktivieren
          cache-dependency-path: 'Moddex-Frontend/package-lock.json'  # Pfad zum Lockfile :contentReference[oaicite:3]{index=3}

      # 7) Frontend bauen
      - name: Build frontend dist
        run: |
          pushd Moddex-Frontend
          npm ci
          npm run build --if-present || npm run build
          popd
          mkdir -p build/frontend
          rsync -a --delete Moddex-Frontend/dist/ build/frontend/
        # Falls dein Angular-Build in einen anderen Ordner schreibt,
        # passe den rsync-Pfad entsprechend an.

      # 8) Bundle zusammenstellen (Skripte/Templates + Artefakte)
      - name: Assemble bundle
        run: |
          mkdir -p bundle/scripts bundle/packaging/systemd bundle/packaging/caddy bundle/config/defaults bundle/frontend bundle/backend
          # Artefakte
          cp -r build/frontend/* bundle/frontend/
          cp -r build/backend/Moddex-Backend.jar bundle/backend/
          # Packaging-Inhalte aus DIESEM Repo
          cp -r scripts/* bundle/scripts/
          cp -r packaging/systemd/* bundle/packaging/systemd/
          cp -r packaging/caddy/* bundle/packaging/caddy/
          if [ -d config/defaults ]; then cp -r config/defaults/* bundle/config/defaults/ || true; fi

          # Tarball + Checksum
          tar -C bundle -czf moddex-${{ github.ref_name }}-linux-amd64.tar.gz .
          sha256sum moddex-${{ github.ref_name }}-linux-amd64.tar.gz > moddex-${{ github.ref_name }}-SHA256SUMS

      # 9) Release erstellen und Assets hochladen
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            moddex-${{ github.ref_name }}-linux-amd64.tar.gz
            moddex-${{ github.ref_name }}-SHA256SUMS
        # Hinweis: dieser Step setzt voraus, dass das Event ein Tag-Push ist
        # und dass das Job-Permission 'contents: write' gesetzt ist. :contentReference[oaicite:4]{index=4}
